
# --------------------------------------------------------
# Runner
# --------------------------------------------------------

ARG BASE_IMG_TAG=nonroot

FROM osmosis:debug as build

FROM gcr.io/distroless/base-debian11:${BASE_IMG_TAG}

COPY --from=build /osmosis/build/osmosisd /bin/osmosisd

ENV HOME /osmosis
WORKDIR $HOME

EXPOSE 26656
EXPOSE 26657
EXPOSE 1317

ENTRYPOINT ["osmosisd"]
CMD [ "start" ]
